evaluations:
  # LLM judge evaluation for group message interventions
  - name: group_msg_interventions_relevance_judge
    function: llm_judge_evaluation
    args:
      judge_prompt_name: group_msg_interventions_relevance_judge
      judge_prompt_version: 3
