evaluations:
  # Simple exact match comparison of the affect field
  # - name: exact_match_affect
  #   function: simple_exact_comparison
  #   key: affect

  # List inclusion comparison to check if output is in a list of expected values
  - name: exact_match_affect
    function: list_inclusion_comparison
    key: affect

  - name: negative_affects
    function: list_inclusion_comparison
    key: affect
    score_only_for: [
        "Partner-Anger",
        "Partner-Belligerence",
        "Partner-Contempt",
        "Partner-Criticism",
        "Partner-Defensiveness",
        "Partner-Disgust",
        "Partner-Domineering",
        "Partner-Fear / Tension",
        "Partner-Sadness",
        "Stonewalling",
        "Partner-Threats",
        "Partner-Whining",
    ]  # Only score if expected output contains any of these emotions

  # LLM judge evaluation for the whole response
  # - name: llm_quality_score
  #   function: llm_judge_evaluation
  #   key: affect
  #   args:
  #     judge_prompt_name: quality_judge
  #     judge_prompt_version: 5
