evaluations:
  # Simple exact match comparison of the affect field
  # - name: exact_match_affect
  #   function: simple_exact_comparison
  #   key: affect


  # Eval setup for message_enricher prompt

  # List inclusion comparison to check if output is in a list of expected values
  - name: exact_match_affect
    function: list_inclusion_comparison
    key: affect

  - name: negative_affects_expected
    function: list_inclusion_comparison
    key: affect
    score_only_for:
      - "Partner-Anger"
      - "Partner-Belligerence"
      - "Partner-Contempt"
      - "Partner-Criticism"
      - "Partner-Defensiveness"
      - "Partner-Disgust"
      - "Partner-Domineering"
      - "Partner-Fear / Tension"
      - "Partner-Sadness"
      - "Stonewalling"
      - "Partner-Threats"
      - "Partner-Whining"
    filter_by: expected

  - name: negative_affects_output
    function: list_inclusion_comparison
    key: affect
    score_only_for:
      - "Partner-Anger"
      - "Partner-Belligerence"
      - "Partner-Contempt"
      - "Partner-Criticism"
      - "Partner-Defensiveness"
      - "Partner-Disgust"
      - "Partner-Domineering"
      - "Partner-Fear / Tension"
      - "Partner-Sadness"
      - "Stonewalling"
      - "Partner-Threats"
      - "Partner-Whining"
    filter_by: output

  - name: positive_affects_expected
    function: list_inclusion_comparison
    key: affect
    score_only_for:
      - "Humor"
      - "Partner-Affection"
      - "Partner-Enthusiasm"
      - "Partner-Interest"
      - "Partner-Validation"
    filter_by: expected

  - name: positive_affects_output
    function: list_inclusion_comparison
    key: affect
    score_only_for:
      - "Humor"
      - "Partner-Affection"
      - "Partner-Enthusiasm"
      - "Partner-Interest"
      - "Partner-Validation"
    filter_by: output


  # Eval setup for 1on1 prompt

  # # LLM judge evaluation for the whole response
  # - name: 1on1_relevance_judge
  #   function: llm_judge_evaluation
  #   args:
  #     judge_prompt_name: 1on1_relevance_judge
  #     judge_prompt_version: 2
