evaluations:
  # Simple exact match comparison of the affect field
  # - name: exact_match_affect
  #   function: simple_exact_comparison
  #   key: affect
  
  # List inclusion comparison to check if output is in a list of expected values
  - name: exact_match_affect
    function: list_inclusion_comparison
    key: affect
  
  # LLM judge evaluation for the whole response
  - name: llm_quality_score
    function: llm_judge_evaluation
    args:
      judge_prompt_name: quality_judge
      judge_prompt_version: 5
  
  # # LLM judge evaluation for just the affect field
  # - name: llm_affect_judge
  #   function: llm_judge_evaluation
  #   key: affect
  #   args:
  #     judge_prompt_name: affect_judge
  #     judge_prompt_version: 1 